version: '3.3'

services:
    app:
        build: .
        container_name: appi
        restart: on-failure
        expose: [1234]
        network_mode: "host"

    postgres:
        container_name: postgres-dev
        restart: on-failure
        image: postgres:alpine3.17
        ports:
        - "5432:5432"
        # volumes:
        # - .docker/postgres:/var/lib/postgresql/data
        environment:
          POSTGRES_PASSWORD: ${DB_PASS}
          POSTGRES_USER: ${DB_USER}
          POSTGRES_DB: ${DB_NAME}

    adminer:
        container_name: adminer-dev
        restart: on-failure
        image: adminer:4.8.0-standalone
        ports:
        - "8080:8080"
        links:
        - postgres:apivendas

    redis:
        container_name: redis-dev
        restart: on-failure
        image: redis:alpine3.17 
        ports:
        - "6379:6379"
        environment:
            REDIS_ARGS: "--requirepass ${REDIS_PASS}" 
